<Project><PropertyGroup><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings><LangVersion>latest</LangVersion><Version Condition="'$(Version)' == ''">0.1.0</Version><Company>Csomaika</Company><Product>SMC Wireless Studio</Product><Deterministic>true</Deterministic></PropertyGroup></Project>
