using System.Windows;
using System.Windows.Controls;
using Studio.Core;
namespace Studio.Desktop;
public sealed partial class MainWindow
{
    private UIElement Logic()
    {
        if(project.Sequences.Count==0)return Page("Vezérlési logika","Még nincs szekvencia.",Ui.Button("+ Szekvencia",AddSequence,true));
        sequenceIndex=Math.Clamp(sequenceIndex,0,project.Sequences.Count-1);var seq=project.Sequences[sequenceIndex];stepIndex=Math.Clamp(stepIndex,0,seq.Steps.Count-1);var step=seq.Steps[stepIndex];
        var sequencePicker=new ComboBox{ItemsSource=project.Sequences,DisplayMemberPath="Name",SelectedIndex=sequenceIndex};sequencePicker.SelectionChanged+=(_,_)=>{sequenceIndex=sequencePicker.SelectedIndex;stepIndex=0;Navigate(3);};
        var state=Ui.Text("",14,Ui.Green);refreshers.Add(s=>state.Text="Állapot: "+s.SequenceStatus);
        var list=Ui.Stack(sequencePicker,state);for(int i=0;i<seq.Steps.Count;i++){int index=i;var item=seq.Steps[i];var detail=item.Kind==StepKind.Delay?item.DurationMs+" ms":$"R{item.RemoteId:00} · {(item.Kind==StepKind.SetOutput?"DO":"DI")}{item.Channel:00} = {(item.Value?1:0)}";var button=Ui.Button(item.Name,()=>{stepIndex=index;Navigate(3);},i==stepIndex);button.Content=Ui.Stack(Ui.Text($"{i+1:00}  {item.Name}",17,null,true),Ui.Text(detail,13,Ui.Muted));button.HorizontalContentAlignment=HorizontalAlignment.Left;list.Children.Add(button);}
        var name=Ui.Input(step.Name,"Lépés neve");var kinds=new ComboBox{ItemsSource=new[]{"Várakozás bemenetre","Kimenet beállítása","Várakozás (idő)"},SelectedIndex=(int)step.Kind};var remotes=new ComboBox{ItemsSource=project.Remotes,DisplayMemberPath="Name",SelectedValuePath="Id",SelectedValue=step.RemoteId};var channel=new ComboBox{ItemsSource=Enumerable.Range(0,8).ToArray(),SelectedItem=step.Channel};var value=new CheckBox{Content="Elvárt / beállított állapot: BE",IsChecked=step.Value};var duration=Ui.Input(step.DurationMs.ToString(),"Tartási idő ms");var timeout=Ui.Input(step.TimeoutMs.ToString(),"Időtúllépés ms");
        var editor=Ui.Card(Ui.Stack(Ui.Field("LÉPÉSNÉV",name),Ui.Field("TÍPUS",kinds),Ui.Field("REMOTE",remotes),Ui.Field("CSATORNA (0-TÓL)",channel),value,Ui.Field("VÁRAKOZÁSI IDŐ (ms)",duration),Ui.Field("BEMENETI HATÁRIDŐ (ms)",timeout),Ui.Button("Lépés mentése",()=>{RequireStopped();var candidate=project.Clone();var edit=candidate.Sequences[sequenceIndex].Steps[stepIndex];edit.Name=name.Text.Trim();edit.Kind=(StepKind)kinds.SelectedIndex;edit.RemoteId=(int)remotes.SelectedValue;edit.Channel=(int)channel.SelectedItem;edit.Value=value.IsChecked==true;if(!int.TryParse(duration.Text,out int d)||!int.TryParse(timeout.Text,out int t))throw new InvalidOperationException("Az időértékek egész számok legyenek.");edit.DurationMs=d;edit.TimeoutMs=t;candidate.Validate();project=candidate;ApplyEdit();Navigate(3);},true),Ui.Text("Bemeneti időtúllépéskor a demószekvencia leáll és a demókimenetek kikapcsolnak.",12,Ui.Muted)),"Lépés beállításai");
        return Page("Vezérlési logika","Bemeneti feltételek, kimenetkapcsolás és időzítés. A mintalogika demóhoz készült.",Ui.Row(RunControls(),Ui.Button("▶ Lépéssor futtatása",()=>engine.StartSequence(sequenceIndex),true),Ui.Button("+ Szekvencia",AddSequence)),Ui.Columns(Ui.Card(Ui.Stack(list,Ui.Row(Ui.Button("+ Lépés",()=>{RequireStopped();seq.Steps.Add(new(){Name="Új lépés",RemoteId=selected,Kind=StepKind.Delay});stepIndex=seq.Steps.Count-1;ApplyEdit();Navigate(3);}),Ui.Button("↑ Fel",()=>MoveStep(-1)),Ui.Button("↓ Le",()=>MoveStep(1)),Ui.Button("Lépés törlése",()=>{RequireStopped();if(seq.Steps.Count<=1)throw new InvalidOperationException("Legalább egy lépés szükséges.");seq.Steps.RemoveAt(stepIndex);stepIndex=Math.Max(0,stepIndex-1);ApplyEdit();Navigate(3);}))),"Szekvencia"),editor,1.5));
    }
    private void AddSequence(){RequireStopped();var name=Ui.Prompt(this,"Szekvencia neve","Új szekvencia");if(name==null)return;StudioProject.CheckName(name,"Név");project.Sequences.Add(new(){Name=name,Steps=[new(){Name="Várakozás",Kind=StepKind.Delay,RemoteId=selected}]});sequenceIndex=project.Sequences.Count-1;stepIndex=0;ApplyEdit();Navigate(3);}
    private void MoveStep(int direction){RequireStopped();var steps=project.Sequences[sequenceIndex].Steps;int next=stepIndex+direction;if(next<0||next>=steps.Count)return;(steps[stepIndex],steps[next])=(steps[next],steps[stepIndex]);stepIndex=next;ApplyEdit();Navigate(3);}
}
