using System.IO;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using Studio.Core;
using Microsoft.Win32;
namespace Studio.Desktop;
public sealed partial class MainWindow
{
    private UIElement IoPanel(bool full)
    {
        var r=Selected;var body=Ui.Stack();var picker=new ComboBox{ItemsSource=project.Remotes,DisplayMemberPath="Name",SelectedValuePath="Id",SelectedValue=selected};picker.SelectionChanged+=(_,_)=>{if(picker.SelectedValue is int id&&id!=selected){selected=id;Navigate(pageIndex);}};body.Children.Add(picker);body.Children.Add(Ui.Text($"R{selected:00} · {r.Name}",17,null,true));
        var inputs=Ui.Stack(Ui.Text("BEMENETEK",12,Ui.Muted,true));
        for(int i=0;i<(full?8:4);i++){int ch=i;var indicator=Ui.Text("● 0",14,Ui.Muted,true);var label=Ui.Button(r.Inputs[i],()=>RenameSignal(false,ch));label.HorizontalContentAlignment=HorizontalAlignment.Left;label.ToolTip="Jel átnevezése (leállítva)";var state=Ui.Button("Átváltás",()=>{var current=engine.Snapshot().Remotes.First(x=>x.Id==selected);engine.SetInput(selected,ch,!current.Inputs[ch]);});state.ToolTip="Demóbemenet váltása, automatikus szenzorok kikapcsolásával";var row=new DockPanel();DockPanel.SetDock(indicator,Dock.Right);row.Children.Add(indicator);if(full){DockPanel.SetDock(state,Dock.Right);row.Children.Add(state);}var content=Ui.Stack(Ui.Text("DI"+i.ToString("00"),11,Ui.Muted),label);row.Children.Add(content);inputs.Children.Add(row);refreshers.Add(s=>{var value=s.Remotes.First(x=>x.Id==selected).Inputs[ch];indicator.Text=value?"● 1":"○ 0";indicator.Foreground=value?Ui.Green:Ui.Muted;});}
        var outputs=Ui.Stack(Ui.Text("KIMENETEK",12,Ui.Muted,true));for(int i=0;i<4;i++){int ch=i;var toggle=Ui.Button("KI",()=>{var current=engine.Snapshot().Remotes.First(x=>x.Id==selected);engine.SetOutput(selected,ch,!current.Outputs[ch]);},true);toggle.MinWidth=64;var label=Ui.Button(r.Outputs[i],()=>RenameSignal(true,ch));label.ToolTip="Jel átnevezése (leállítva)";label.HorizontalContentAlignment=HorizontalAlignment.Left;var row=new DockPanel();DockPanel.SetDock(toggle,Dock.Right);row.Children.Add(toggle);row.Children.Add(Ui.Stack(Ui.Text("DO"+i.ToString("00"),11,Ui.Muted),label));outputs.Children.Add(row);refreshers.Add(s=>{var remote=s.Remotes.First(x=>x.Id==selected);toggle.Content=remote.Outputs[ch]?"BE":"KI";toggle.Background=remote.Outputs[ch]?Ui.Brush("#078BE1"):Ui.Brush("#20384B");toggle.IsEnabled=s.Running&&!s.SequenceRunning&&remote.Online;});}
        body.Children.Add(full?Ui.Columns(Ui.Card(inputs),Ui.Card(outputs),1):Ui.Stack(inputs,outputs));return body;
    }
    private void RenameSignal(bool output,int channel){RequireStopped();var list=output?Selected.Outputs:Selected.Inputs;var name=Ui.Prompt(this,"Jel átnevezése",list[channel]);if(name==null)return;StudioProject.CheckName(name,"Jelnév");list[channel]=name;ApplyEdit();Navigate(pageIndex);}
    private UIElement IoMonitor(){var automatic=new CheckBox{Content="Automatikus demószenzorok",IsChecked=engine.AutomaticSensors};automatic.Click+=(_,_)=>engine.AutomaticSensors=automatic.IsChecked==true;return Page("I/O monitor","Jelnévre kattintva átnevezés. A bemenetek demóban kézzel is változtathatók.",Ui.Row(RunControls(),automatic),Ui.Card(IoPanel(true),"Kézi I/O-vezérlés"));}
    private UIElement LogRows(int limit=200)
    {
        var rows=new StackPanel();DateTime last=DateTime.MinValue;
        refreshers.Add(_=>{var all=engine.Logs();var latest=all.FirstOrDefault()?.Time??DateTime.MinValue;if(latest==last)return;last=latest;rows.Children.Clear();var query=all.Where(x=>(logLevel=="Összes"||x.Level==logLevel)&&(x.Message+" "+x.Device).Contains(logSearch,StringComparison.CurrentCultureIgnoreCase)).Take(limit);foreach(var log in query){var line=new Grid{Margin=new Thickness(0,0,0,8)};line.ColumnDefinitions.Add(new(){Width=new GridLength(90)});line.ColumnDefinitions.Add(new(){Width=new GridLength(95)});line.ColumnDefinitions.Add(new(){Width=new GridLength(130)});line.ColumnDefinitions.Add(new(){Width=new GridLength(1,GridUnitType.Star)});string[] parts=[log.Time.ToString("HH:mm:ss"),log.Level,log.Device,log.Message];for(int i=0;i<4;i++){var t=Ui.Text(parts[i],12,i==1&&log.Level!="INFO"?Ui.Amber:Ui.Muted);t.Margin=new Thickness(0,0,12,3);Grid.SetColumn(t,i);line.Children.Add(t);}rows.Children.Add(line);}if(rows.Children.Count==0)rows.Children.Add(Ui.Text("Nincs a szűrőnek megfelelő esemény.",14,Ui.Muted));});return rows;
    }
    private UIElement EventLog(){var search=Ui.Input(logSearch,"Esemény keresése");var levels=new ComboBox{ItemsSource=new[]{"Összes","INFO","FIGYELEM","HIBA"},SelectedItem=logLevel,Width=160};return Page("Eseménynapló","Az utolsó 2 000 esemény; a legutóbbi munkamenet naplója kilépéskor mentésre kerül.",Ui.Card(Ui.Stack(Ui.Columns(search,Ui.Row(levels,Ui.Button("Szűrés",()=>{logSearch=search.Text;logLevel=(string)levels.SelectedItem;Navigate(4);}),Ui.Button("CSV export",ExportLog)),2),LogRows()),"Események"));}
    private void ExportLog(){var dialog=new SaveFileDialog{FileName="SMC-Wireless-naplo.csv",Filter="CSV napló|*.csv"};if(dialog.ShowDialog(this)==true){File.WriteAllText(dialog.FileName,DemoEngine.ExportCsv(engine.Logs()),System.Text.Encoding.UTF8);toast.Text="Napló exportálva.";}}
    private UIElement Projects()
    {
        var saved=Ui.Stack();foreach(var file in store.Files()){try{var p=store.Load(file);saved.Children.Add(Ui.Card(Ui.Stack(Ui.Text(p.Customer,13,Ui.Muted),Ui.Text($"{p.Remotes.Count} remote · {p.Sequences.Count} szekvencia · {p.CycleMs} ms",13,Ui.Muted),Ui.Button("Megnyitás",()=>LoadProject(p))),p.Name));}catch(Exception ex){saved.Children.Add(Ui.Card(Ui.Text(Path.GetFileName(file)+": "+ex.Message,13,Ui.Amber),"Nem olvasható projekt"));}}
        if(saved.Children.Count==0)saved.Children.Add(Ui.Text("Még nincs mentett projekt. A felső Projekt mentése gombbal mentheted az aktuális demót.",15,Ui.Muted));
        var name=Ui.Input(project.Name,"Projektnév");var customer=Ui.Input(project.Customer,"Ügyfél");var detail=Ui.Card(Ui.Stack(Ui.Field("PROJEKTNÉV",name),Ui.Field("ÜGYFÉL",customer),Ui.Button("Adatok mentése",()=>{RequireStopped();StudioProject.CheckName(name.Text,"Projektnév");StudioProject.CheckName(customer.Text,"Ügyfél");project.Name=name.Text.Trim();project.Customer=customer.Text.Trim();ApplyEdit();SaveProject();Navigate(5);},true),Ui.Button("Másolat készítése",()=>{RequireStopped();var clone=project.Clone();clone.Id=Guid.NewGuid();clone.Name=project.Name.Length>88?project.Name[..88]+" – másolat":project.Name+" – másolat";store.Save(clone);Navigate(5);}),Ui.Button("Projekt exportálása",ExportProject),Ui.Text("A projektnevek, jelnevek és lépések megmaradnak verziófrissítéskor is.",13,Ui.Muted),Ui.Button("Projektmappa megnyitása",()=>System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo(store.Root){UseShellExecute=true}))),"Aktuális projekt");
        return Page("Projektek","Saját konfigurációk, importálás és biztonsági másolatok.",Ui.Row(Ui.Button("+ Új demóprojekt",()=>{RequireStopped();LoadProject(StudioProject.Demo());MarkDirty();},true),Ui.Button("Projekt importálása",ImportProject)),Ui.Columns(saved,detail,1.5));
    }
    private void LoadProject(StudioProject next){RequireStopped();if(dirty&&MessageBox.Show(this,"Az aktuális módosításokat elveted?","Projekt megnyitása",MessageBoxButton.YesNo)!=MessageBoxResult.Yes)return;next.Validate();project=next.Clone();engine.ApplyConfig(project);selected=project.Remotes[0].Id;sequenceIndex=stepIndex=0;dirty=false;networkSearch="";onlyFaulty=false;engine.AddLog("INFO","Projekt","Betöltve: "+project.Name);Navigate(0);}
    private void ImportProject(){RequireStopped();var dialog=new OpenFileDialog{Filter="Studio projekt|*.smcws.json;*.json"};if(dialog.ShowDialog(this)!=true)return;var imported=store.Load(dialog.FileName);imported.Id=Guid.NewGuid();LoadProject(imported);if(project.Id==imported.Id){SaveProject();Navigate(5);}}
    private void ExportProject(){var dialog=new SaveFileDialog{FileName="Wireless-projekt.smcws.json",Filter="Studio projekt|*.smcws.json"};if(dialog.ShowDialog(this)==true){store.Export(project,dialog.FileName);toast.Text="Projekt exportálva.";}}
    private UIElement Settings()
    {
        var baseName=Ui.Input(project.BaseName,"Base neve");var ip=Ui.Input(project.BaseIp,"Base IPv4 címe");var port=Ui.Input(project.Port.ToString(),"TCP port");
        var connection=Ui.Card(Ui.Stack(Ui.Field("BASE MEGJELENÍTETT NEVE",baseName),Ui.Field("BASE IPv4-CÍM",ip),Ui.Field("TCP PORT",port),Ui.Button("Beállítások mentése",()=>{RequireStopped();var candidate=project.Clone();candidate.BaseName=baseName.Text.Trim();candidate.BaseIp=ip.Text.Trim();if(!int.TryParse(port.Text,out var n))throw new InvalidDataException("Érvénytelen port.");candidate.Port=n;candidate.Validate();project=candidate;ApplyEdit();SaveProject();Navigate(6);},true),Ui.Text("A címek ebben a kiadásban projektadatok. A demó nem nyit kapcsolatot a base felé.",13,Ui.Muted)),"Kommunikáció");
        var mode=Ui.Card(Ui.Stack(Ui.Badge("DEMÓ · Szimulált I/O"),Ui.Text("Valódi I/O illesztés",18,null,true),Ui.Text("A hardveres kiadáshoz a pontos base-típus, firmware és a dokumentált regisztertérkép szükséges.",14,Ui.Muted),Ui.Text("Itt most az alkalmazás működését, a neveket és a logikát próbálhatod ki valódi kimenetek kapcsolása nélkül.",14,Ui.Muted)),"Működési mód");
        var timing=Ui.Card(Ui.Stack(CycleSelector(),Ui.Text("Módosítás csak leállított vezérlésnél.",13,Ui.Muted),Ui.Text("A ciklus a kezelőfelülettől külön fut. Az állapotsáv valós mért időket mutat; a Windows nem garantál kemény valós idejű határidőt.",13,Ui.Muted)),"Ciklusidő");
        var updates=Ui.Card(Ui.Stack(Ui.Text("Telepített verzió: "+CurrentVersion.ToString(3),17,null,true),Ui.AsyncButton("Update · Frissítés keresése",CheckUpdates,true),Ui.Text("Az új verziót a projekt GitHub Releases oldaláról töltjük le. Az MSI frissítési útvonala megtartja a projekteket.",13,Ui.Muted),Ui.Button("Kiadások megnyitása",()=>System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo("https://github.com/"+ReleaseVersion.Repository+"/releases"){UseShellExecute=true}))),"Frissítések");
        return Page("Beállítások","Kommunikáció, időzítés és verziófrissítések.",Ui.Columns(connection,mode,1),Ui.Columns(timing,updates,1));
    }
}
